Repository jenkinsci/custom-distribution-service, pull requests merged in 2020-08, with the labels that each got.

#100 Add navigation for community configurations
  frontend/src/components/layouts/Header.js
Labels: frontend

#103 Add jacoco code coverage report generation
  pom.xml
Labels: backend

#102 Add PMD for static analysis
  config/pmd.xml
  pom.xml
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/CustomJenkinsDistributionServiceApplication.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/IndexController.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/PackagerController.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/PluginController.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/generators/PackageConfigGenerator.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/generators/WarGenerator.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/services/PackagerDownloadService.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/services/UpdateCenterService.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/util/Util.java
Labels: chore

#105 Add Update Center Service Test
  pom.xml
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/services/UpdateCenterService.java
  src/test/java/com/org/jenkins/custom/jenkins/distribution/service/services/UpdateCenterServiceTest.java
Labels: backend

#136 Add release-drafter configuration
  .github/workflows/changelog.yml
Labels: chore

#119 Add appropriate message if empty bundle
  frontend/src/components/PackageGeneration/Editor.js
Labels: frontend

#133 Add packager Controller Tests
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/PackagerController.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/generators/PackageConfigGenerator.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/generators/WarGenerator.java
  src/main/java/com/org/jenkins/custom/jenkins/distribution/service/services/PackagerDownloadService.java
  src/main/resources/dummy_war.txt
  src/main/resources/simple-config.json
  src/main/resources/simple-config.yaml
  src/test/java/com/org/jenkins/custom/jenkins/distribution/service/PackagerControllerTest.java
  src/test/java/com/org/jenkins/custom/jenkins/distribution/service/PluginControllerTest.java
  src/test/java/com/org/jenkins/custom/jenkins/distribution/service/SpringMVCSetup.java
  src/test/java/com/org/jenkins/custom/jenkins/distribution/service/generators/PackageConfigGeneratorTest.java
Labels: test

#152 Accept long variable names
  config/pmd.xml
Labels: chore

#145 Add user docs
  README.md
  docs/USAGE.md
  images/cds_gsoc.png
  images/community_config.png
  images/editor.png
  images/package_generation.png
  images/plugins_page.png
Labels: documentation
